### ISSUE TITLE
Function that fetches Entrez IDs is not working anymore

### ISSUE THREAD

**Issue by ievarau** [wassermanlab/gene2wordclouds#3]
Hello,

UniProt has updated their API in 2022 October. This means that the way Entrez IDs were retrieved is not working anymore. We found a way to update the function to accommodate the updated API.

This is the updated function in the file `gene2wordclouds/utils/uniacc2entrezid.py`:

```python
def __get_uniaccs_entrezids(uniaccs):

    uniaccs_entrezids = []
    gcontext = ssl.SSLContext()
    url = "https://rest.uniprot.org/idmapping/run"
    params = {
        "from": "UniProtKB_AC-ID",
        "to": "GeneID",
        "ids": " ".join(list(uniaccs))
    }

    # Get Entrez Gene IDs
    params = parse.urlencode(query=params).encode("utf-8")
    req = request.Request(url, params)
    with request.urlopen(req, context=gcontext) as handle:
        response = handle.read().decode("utf-8")
        response = json.loads(response)
        jobid = response["jobId"]
    url_jobid = f"https://rest.uniprot.org/idmapping/results/{jobid}"
    req_jobid = request.Request(url_jobid)
    with request.urlopen(req_jobid, context=gcontext) as handle:
        result = handle.read().decode("utf-8")
        result = json.loads(result)
    for r in result['results']:
        if 'to' in r.keys():
            uniaccs_entrezids.append([r['from'], int(r['to'])])

    return(uniaccs_entrezids)
```

It would be great to include this update, so the package works as expected.

Best,
Ieva

**Comment by ievarau** [comment]
For this function to work, the environment config file should also include `json` package then.

**Comment by oriolfornes** [comment]
Good catch. I just implemented the suggested modifications.

**Comment by ievarau** [comment]
Hei, Oriol!

Thanks for updating with our suggestion, but could you revise the script one more time? There seems to be a duplication in function and one of them just has ```return```. I guess it was left there by accident.

Thanks!
Ieva

**Comment by oriolfornes** [comment]
I think it's fixed now :) Good catch!

**Comment by ievarau** [comment]
Ok, one more thing :sweat_smile: The ```query``` now is change to ```ids```, so params should be changed (see above in the function). With ```query``` it crashes. Sorry too bother and thanks for the help! :smile:

**Comment by oriolfornes** [comment]
No worries, I should have copy-pasted the whole function but I just edited
the lines that were different. Hope it works well now!
—
*Oriol Fornés Crespo, PhD*
Computational Biologist
